<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Eu4bFr\Odoswitch_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Eu4bFr/Odoswitch_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2Eu4bFr.legacy');

    return;
}

if (!\class_exists(Odoswitch_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2Eu4bFr\Odoswitch_KernelDevDebugContainer::class, Odoswitch_KernelDevDebugContainer::class, false);
}

return new \Container2Eu4bFr\Odoswitch_KernelDevDebugContainer([
    'container.build_hash' => '2Eu4bFr',
    'container.build_id' => '681cd840',
    'container.build_time' => 1720399992,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Eu4bFr');
