<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGSeT87a\Odoswitch_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGSeT87a/Odoswitch_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGSeT87a.legacy');

    return;
}

if (!\class_exists(Odoswitch_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGSeT87a\Odoswitch_KernelDevDebugContainer::class, Odoswitch_KernelDevDebugContainer::class, false);
}

return new \ContainerGSeT87a\Odoswitch_KernelDevDebugContainer([
    'container.build_hash' => 'GSeT87a',
    'container.build_id' => 'caaf7a38',
    'container.build_time' => 1720972074,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGSeT87a');
