<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHBSp7Qj\Odoswitch_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHBSp7Qj/Odoswitch_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHBSp7Qj.legacy');

    return;
}

if (!\class_exists(Odoswitch_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHBSp7Qj\Odoswitch_KernelDevDebugContainer::class, Odoswitch_KernelDevDebugContainer::class, false);
}

return new \ContainerHBSp7Qj\Odoswitch_KernelDevDebugContainer([
    'container.build_hash' => 'HBSp7Qj',
    'container.build_id' => '12ccb0a2',
    'container.build_time' => 1720995832,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHBSp7Qj');
