<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home' => [[], ['_controller' => 'Odoswitch\\Controller\\Home::index'], [], [['text', '/']], [], [], []],
    'Odoswitch\Controller\Home::index' => [[], ['_controller' => 'Odoswitch\\Controller\\Home::index'], [], [['text', '/']], [], [], []],
];
